/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyGraphics;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;

public class Draw extends javax.swing.JFrame {

    Color color = Color.RED;

    /**
     * Creates new form DrawWithMouse
     */
    public Draw() {
        super();
        initComponents();
        this.setSize(600, 600);
        ButtonGroup btng = new ButtonGroup();
        btng.add(rbtDrawOnly);
        btng.add(rbtDrawFill);
        this.rbtDrawOnly.setSelected(true);
        this.rbtDrawFill.setEnabled(false);

        pnlLines.c = color;
        pnlEllipse.c = color;
        pnlRectangles.c = color;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnColor = new javax.swing.JButton();
        rbtDrawOnly = new javax.swing.JRadioButton();
        rbtDrawFill = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlLines = new MyLine();
        pnlEllipse = new MyEllipse();
        pnlRectangles = new MyRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnColor);

        rbtDrawOnly.setText("Draw Only");
        rbtDrawOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //rbtDrawOnlyActionPerformed(evt);
                pnlEllipse.isFilled = rbtDrawOnly.isSelected();
                pnlRectangles.isFilled = rbtDrawOnly.isSelected();
            }
        });
        jPanel1.add(rbtDrawOnly);

        rbtDrawFill.setText("Draw and Fill");
        rbtDrawFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });

        jPanel1.add(rbtDrawFill);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

            }
        });

        jTabbedPane1.addTab("Lines", pnlLines);
        jTabbedPane1.addTab("Ellipses", pnlEllipse);
        jTabbedPane1.addTab("Rectangles", pnlRectangles);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int index = this.jTabbedPane1.getSelectedIndex();
        switch (index) {
            case 0:
                this.rbtDrawOnly.setEnabled(true);
                this.rbtDrawFill.setEnabled(false);
                break;
            case 1:
                this.rbtDrawFill.setEnabled(true);
                break;
            case 2:
                this.rbtDrawFill.setEnabled(true);
                break;
        }
        pnlLines.shapes.clear();
        pnlEllipse.shapes.clear();
        pnlRectangles.shapes.clear();
    }

    private void rbtDrawOnlyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JColorChooser jcc = new JColorChooser();
        color = JColorChooser.showDialog(this, "Change color", color);
        pnlLines.c = color;
        pnlEllipse.c = color;
        pnlRectangles.c = color;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnColor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private MyEllipse pnlEllipse;
    private MyLine pnlLines;
    private MyRectangle pnlRectangles;
    private javax.swing.JRadioButton rbtDrawFill;
    private javax.swing.JRadioButton rbtDrawOnly;
    // End of variables declaration                   
}
