/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocketChat;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import static java.lang.Thread.sleep;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author ducltm
 */
public class ChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatPanel
     */
    Socket socket = null;
    BufferedReader bf = null;
    DataOutputStream os = null;
    OutputThread t = null;
    String receiver;
    String sender;

    public ChatPanel(Socket s, String sender, String receiver) {
        initComponents();
        socket = s;
        this.sender = sender;
        this.receiver = receiver;
        try {
            bf = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            os = new DataOutputStream(socket.getOutputStream());
            t = new OutputThread(s, txtMessages, sender, receiver);
            t.start();
        } catch (Exception e) {
        }
    }

    public JTextArea getTxtMessages() {
        return this.txtMessages;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();
        pnlMessage = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnSendFile = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        txtMessages.setColumns(20);
        txtMessages.setRows(5);
        jScrollPane3.setViewportView(txtMessages);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnlMessage.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));
        pnlMessage.setLayout(new java.awt.GridLayout(1, 0));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane4.setViewportView(txtMessage);

        pnlMessage.add(jScrollPane4);

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlMessage.add(btnSend);

        btnSendFile.setText("Send File");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });
        pnlMessage.add(btnSendFile);

        add(pnlMessage, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (txtMessage.getText().trim().length() == 0) {
            return;
        }
        try {
            String S = "T" + txtMessage.getText();
            os.writeBytes(S);
            os.writeByte(13);
            os.writeByte(10);
            os.flush();
            txtMessages.append("\n" + sender + ": " + txtMessage.getText());
            txtMessage.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
        // TODO add your handling code here:
        try {
            int result = fc.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                if (f.isFile()) {
                    FileReader fr = new FileReader(f);
                    BufferedReader br = new BufferedReader(fr);
                    String S = "";
                    String content = "F";

                    while ((S = br.readLine()) != null) {
                        content = content + S + "@#$%^";
                    }

                    os.writeBytes("TSent a file from " + sender);
                    os.writeByte(13);
                    os.writeByte(10);
                    os.flush();

                    txtMessages.append("\n" + sender + ": " + "File is sending.");

                    String cont = content;
                    Runnable r = new Runnable() {
                        @Override
                        public void run() {
                            try {
                                sleep(30000);
                                os.writeBytes(cont);
                                os.writeByte(13);
                                os.writeByte(10);
                                os.flush();
                            } catch (Exception ex) {
                                Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    };
                    Thread t = new Thread(r);

                    br.close();
                    fr.close();
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSendFileActionPerformed

    final JFileChooser fc = new JFileChooser();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables
}
